/*
 * Copyright 2015-2022 Transmogrify LLC, 2022-2026 Revetware LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pyranid;

import org.jspecify.annotations.NonNull;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.utility.DockerImageName;

import javax.sql.DataSource;

/**
 * @author <a href="https://www.revetkn.com">Mark Allen</a>
 * @since 4.3.0
 */
@Testcontainers
public class OracleIntegrationIT extends AbstractPortableJdbcIntegrationTests {
	private static final String ORACLE_IMAGE_NAME =
			System.getProperty("oracle.integration.image", "gvenzl/oracle-free:23-slim-faststart");
	private static final DockerImageName ORACLE_IMAGE = DockerImageName.parse(ORACLE_IMAGE_NAME)
			.asCompatibleSubstituteFor("gvenzl/oracle-free");

	@Container
	private static final OracleContainer ORACLE = new OracleContainer(ORACLE_IMAGE)
			.withUsername("pyranid")
			.withPassword("pyranid");

	@NonNull
	@Override
	protected DataSource dataSource() {
		return new DriverManagerDataSource(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword());
	}

	@NonNull
	@Override
	protected DatabaseType expectedDatabaseType() {
		return DatabaseType.ORACLE;
	}

	@NonNull
	@Override
	protected DialectProfile dialectProfile() {
		return new DialectProfile() {
			@NonNull
			@Override
			String bigIntPrimaryKey() {
				return "NUMBER(19,0) PRIMARY KEY";
			}

			@NonNull
			@Override
			String bigInt() {
				return "NUMBER(19,0)";
			}

			@NonNull
			@Override
			String integer() {
				return "NUMBER(10,0)";
			}

			@NonNull
			@Override
			String varchar(int length) {
				return "VARCHAR2(" + length + ")";
			}

			@NonNull
			@Override
			String doublePrecision() {
				return "BINARY_DOUBLE";
			}

			@NonNull
			@Override
			String autoIncrementPrimaryKey(@NonNull String columnName) {
				return columnName + " NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
			}

			@NonNull
			@Override
			String generatedKeyColumnName() {
				return "ID";
			}

			@NonNull
			@Override
			String dropTableSql(@NonNull String tableName) {
				return "BEGIN EXECUTE IMMEDIATE 'DROP TABLE " + tableName
						+ "'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;";
			}

			@NonNull
			@Override
			String validationQuery() {
				return "SELECT 1 FROM DUAL";
			}
		};
	}

	@NonNull
	@Override
	protected CapabilityFlags capabilityFlags() {
		return CapabilityFlags.builder()
				.supportsReadOnlyTransactions(false)
				.supportsTemporalRoundTrip(false)
				.hasNativeBoolean(false)
				.build();
	}
}
