/*
 * Copyright 2015-2022 Transmogrify LLC, 2022-2026 Revetware LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pyranid;

import org.jspecify.annotations.NonNull;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.utility.DockerImageName;

import javax.sql.DataSource;
import java.nio.ByteBuffer;
import java.util.UUID;

/**
 * @author <a href="https://www.revetkn.com">Mark Allen</a>
 * @since 4.3.0
 */
@Testcontainers
public class OracleIntegrationIT extends AbstractPortableJdbcIntegrationTests {
	private static final String ORACLE_IMAGE_NAME =
			System.getProperty("oracle.integration.image", "gvenzl/oracle-free:23-slim-faststart");
	private static final DockerImageName ORACLE_IMAGE = DockerImageName.parse(ORACLE_IMAGE_NAME)
			.asCompatibleSubstituteFor("gvenzl/oracle-free");

	@Container
	private static final OracleContainer ORACLE = new OracleContainer(ORACLE_IMAGE)
			.withUsername("pyranid")
			.withPassword("pyranid");

	@Test
	public void testOracleGeneratedKeysRejectNoColumnNameBeforeRowIdTrap() {
		Database db = database();
		String table = "pyr_oracle_key_guard";
		recreateTable(db, table, dialectProfile().generatedKeyTableSql(table));

		DatabaseException exception = Assertions.assertThrows(DatabaseException.class, () ->
				db.query("INSERT INTO " + table + " (name) VALUES (:name)")
						.bind("name", "Ada")
						.executeReturningGeneratedKey(Long.class));

		Assertions.assertInstanceOf(IllegalArgumentException.class, exception.getCause());
		Assertions.assertTrue(exception.getMessage().contains("Oracle generated-key retrieval requires explicit key column names"));
		Assertions.assertEquals(0L, countRows(db, table),
				"Oracle no-column generated-key guard should reject before executing the insert");
	}

	@Test
	public void testOracleRawUuidRoundTrip() {
		Database db = database();
		String table = "pyr_oracle_uuid_items";
		UUID id = UUID.fromString("f81d4fae-7dec-11d0-a765-00a0c91e6bf6");
		recreateTable(db, table, "CREATE TABLE " + table + " ("
				+ "id RAW(16) PRIMARY KEY, "
				+ "name VARCHAR2(64) NOT NULL"
				+ ")");

		db.query("INSERT INTO " + table + " (id, name) VALUES (:id, :name)")
				.bind("id", id)
				.bind("name", "raw uuid")
				.execute();

		Assertions.assertEquals(id, db.query("SELECT id FROM " + table)
				.fetchObject(UUID.class)
				.orElseThrow());
		Assertions.assertArrayEquals(uuidBytes(id), db.query("SELECT id FROM " + table)
				.fetchObject(byte[].class)
				.orElseThrow());
	}

	@NonNull
	@Override
	protected DataSource dataSource() {
		return new DriverManagerDataSource(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword());
	}

	@NonNull
	@Override
	protected DatabaseType expectedDatabaseType() {
		return DatabaseType.ORACLE;
	}

	@NonNull
	@Override
	protected DialectProfile dialectProfile() {
		return new DialectProfile() {
			@NonNull
			@Override
			String bigIntPrimaryKey() {
				return "NUMBER(19,0) PRIMARY KEY";
			}

			@NonNull
			@Override
			String bigInt() {
				return "NUMBER(19,0)";
			}

			@NonNull
			@Override
			String integer() {
				return "NUMBER(10,0)";
			}

			@NonNull
			@Override
			String varchar(int length) {
				return "VARCHAR2(" + length + ")";
			}

			@NonNull
			@Override
			String doublePrecision() {
				return "BINARY_DOUBLE";
			}

			@NonNull
			@Override
			String autoIncrementPrimaryKey(@NonNull String columnName) {
				return columnName + " NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
			}

			@NonNull
			@Override
			String generatedKeyColumnName() {
				return "ID";
			}

			@NonNull
			@Override
			String dropTableSql(@NonNull String tableName) {
				return "BEGIN EXECUTE IMMEDIATE 'DROP TABLE " + tableName
						+ "'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;";
			}

			@NonNull
			@Override
			String validationQuery() {
				return "SELECT 1 FROM DUAL";
			}
		};
	}

	@NonNull
	@Override
	protected CapabilityFlags capabilityFlags() {
		return CapabilityFlags.builder()
				.supportsReadOnlyTransactions(false)
				.supportsTemporalRoundTrip(false)
				.hasNativeBoolean(false)
				.build();
	}

	private static byte[] uuidBytes(UUID uuid) {
		ByteBuffer byteBuffer = ByteBuffer.wrap(new byte[16]);
		byteBuffer.putLong(uuid.getMostSignificantBits());
		byteBuffer.putLong(uuid.getLeastSignificantBits());
		return byteBuffer.array();
	}
}
