/*
 * Copyright 2015-2022 Transmogrify LLC, 2022-2026 Revetware LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pyranid;

import org.jspecify.annotations.NonNull;

import static java.lang.String.format;
import static java.util.Objects.requireNonNull;

/**
 * Database-specific SQL vocabulary used by portable integration tests.
 *
 * @author <a href="https://www.revetkn.com">Mark Allen</a>
 * @since 4.3.0
 */
class DialectProfile {
	@NonNull
	static final DialectProfile DEFAULT = new DialectProfile();

	@NonNull
	String bigIntPrimaryKey() {
		return "BIGINT PRIMARY KEY";
	}

	@NonNull
	String bigInt() {
		return "BIGINT";
	}

	@NonNull
	String integer() {
		return "INTEGER";
	}

	@NonNull
	String varchar(int length) {
		return format("VARCHAR(%d)", length);
	}

	@NonNull
	String decimal(int precision,
								 int scale) {
		return format("DECIMAL(%d, %d)", precision, scale);
	}

	@NonNull
	String doublePrecision() {
		return "DOUBLE PRECISION";
	}

	@NonNull
	String date() {
		return "DATE";
	}

	@NonNull
	String time() {
		return "TIME";
	}

	@NonNull
	String timestamp() {
		return "TIMESTAMP";
	}

	@NonNull
	String autoIncrementPrimaryKey(@NonNull String columnName) {
		requireNonNull(columnName);

		return columnName + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
	}

	@NonNull
	String generatedKeyTableSql(@NonNull String tableName) {
		requireNonNull(tableName);

		return "CREATE TABLE " + tableName + " (" + autoIncrementPrimaryKey("id") + ", name " + varchar(64) + " NOT NULL)";
	}

	@NonNull
	String generatedKeyColumnName() {
		return "id";
	}

	@NonNull
	String dropTableSql(@NonNull String tableName) {
		requireNonNull(tableName);

		return "DROP TABLE IF EXISTS " + tableName;
	}

	@NonNull
	String validationQuery() {
		return "SELECT 1";
	}
}
